model_params:
  name: 'VAE1'
  in_channels: 3
  latent_dim: 10

data_params:
  data_path: "Data/"
  train_batch_size: 64
  val_batch_size:  64
  patch_size: 64
  num_workers: 4

trainer_params:
  max_epochs: 10

