vae_raw:
  in_channels:  1
  n_latent  : 128
  ratios :
  - 2
  - 2
  - 2
  - 2
  - 4
  - 4
  - 2
  channel_size: 
  - 8
  - 16
  - 32
  - 64
  - 128
  - 256
  - 512
  model_name : "Run test visu librosa 3"

dataset:
  batch_size: 64
  valid_ratio: 0.99
  num_thread: 0

train:
  lr : 0.0001
  beta : 0.3
  n_fft_l : 
  - 2048
  - 1024
  - 512
  - 256
  w : "Hamming"
  epochs: 10
  save_ckpt: 5
  add_fig_sound: 5