vae_hier:
  n_latent  : 8
  ratios :
  - 2
  - 2
  - 2
  - 2
  channel_size: 
  - 64
  - 128
  - 256
  - 512
  model_name : "Test_2"

train_hier:
  lr : 0.0001
  beta : 0.1
  epochs: 100
  save_ckpt: 5
  add_fig_sound: 5
  loss_type: "mean"

dataset_hier:
  batch_size: 64
  valid_ratio: 0.05
  num_thread: 0