vae_raw:
  in_channels:  1
  n_latent  : 128
  ratios :
  - 4
  - 4
  - 4
  - 4
  channel_size: 
  - 16
  - 32
  - 64
  - 128
  model_name : "Test changement loss type"

dataset:
  batch_size: 64
  valid_ratio: 0.2
  num_thread: 0

train:
  lr : 0.0001
  beta : 1
  n_fft_l : 
  - 4096
  - 2048
  - 1024
  - 512
  - 256
  - 128
  w : "Hamming"
  epochs: 101
  save_ckpt: 5
  add_fig_sound: 5
  loss: "MSE"